name: Actions
on: push
jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-go@v3
       with:
         go-version: '1.18.1' # The Go version to download (if necessary) and use.
     - run: go test .
  deploy:
    name: "deploy"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/live'
    needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.LIVE_SSH_USER }}
          SSH_KEY: ${{ secrets.LIVE_SSH_KEY }}
          SSH_HOST: ${{ secrets.LIVE_SSH_HOST }}

      - name: Stop the server
        run: ssh staging 'sudo supervisorctl stop website'

      - name: Check out the source
        run: ssh staging 'cd website && git fetch && git reset --hard origin/live'

      - name: Start the server
        if: ${{ always() }}
        run: ssh staging 'sudo supervisorctl start website'
