name: Deploy
on:
  pull_request:
    branches: [live]
    types: [closed]
jobs:
  deploy:
    name: "deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.LIVE_SSH_USER }}
          SSH_KEY: ${{ secrets.LIVE_SSH_KEY }}
          SSH_HOST: ${{ secrets.LIVE_SSH_HOST }}

      - name: Stop the server
        run: ssh staging 'supervisorctl stop goserver'

      - name: Check out the source
        run: ssh staging 'cd website && git fetch && git reset --hard origin/live'

      - name: Start the server
        if: ${{ always() }}
        run: ssh staging 'supervisorctl start goserver'
